### ISSUE TITLE
tables_demo_planning: Move in observe pose or not

### ISSUE THREAD

**Issue by alexander-sung** [DFKI-NI/mobipick_labs#28]
Currently, the Mobipick is "allowed" to move its base while the arm is in `observe` pose only during a search action. In this case the robot moves from one table to the next to look for a specific item. Moving the arm back and forth at each table doesn't make sense.

On the other hand, the move actions outside of such a search are only possible in either `home` or `transport` pose, depending on holding an object. If we allow move actions with `observe` pose in general, the robot could plan to move its arm into `observe` just to drive somewhere. In general, it looks a bit strange.

These circumstances combined lead to this particular behavior: If the Mobipick is searching for an item and finds one which it does not need to pick up right now (box being on target table, or replanning decides to get the other item first), it moves its arm from `observe` pose to `home` pose, drives to the next table, just to move the arm to the `observe` pose again. It is not modeled to check for moving between two search actions, when keeping the robot arm in `observe` pose would make sense.

Any thoughts whether this issue needs to be resolved somehow? @sebastianstock, @mintar

**Comment by sebastianstock** [comment]
Hi. In my opinion, the robot's arm should be in a safe pose when driving, which was the motivation for having home and transport as a precondition of the move action. I think in the observe pose the arm and gripper are not completely over the robot's base and therefore collisions with obstacles would be possible. 
Although those arm movements could look strange and unnecessary, I would still keep them because of this - unless we find a way or special move-action that guarantees for two poses that it is safe to be in an observe pose.

**Comment by alexander-sung** [comment]
It would look strange and unnecessary but especially very slow. Since the robot in general operates in a fenced space, it is a reasonable safe movement and thus it would look not so smart to perform all the unnecessary actions in my opinion.

My intended solution was aiming for the opposite direction, so I conclude we probably don't change anything for now.
