### ISSUE TITLE
Resolve trac_ik "deprecated API", pilz "Multi-DOF-Joint" and TF exception "map" warnings on start-up

### ISSUE THREAD

**Issue by alexander-sung** [DFKI-NI/mobipick_labs#3]
On start-up `roslaunch tables_demo_bringup demo_sim.launch`, these warnings appear:

```
IK plugin for group 'arm' relies on deprecated API. Please implement initialize(RobotModel, ...). [/mobipick/move_group]
```
The same warning is shown for `[/mobipick/moveit_macros]` and `[/mobipick/move_group_commander_wrappers_<ID>]` later, most likely due to same root cause.

Later these warnings appear:
```
Multi-DOF-Joint 'mobipick/virtual_joint' not supported. [/mobipick/move_group]
```

```
Unable to update multi-DOF joint 'mobipick/virtual_joint': Failure to lookup transform between 'map' and 'mobipick/base_footprint' with TF exception: "map" passed to lookupTransform argument target_frame does not exist.  [/mobipick/move_group]
```

**Comment by mintar** [comment]
> IK plugin for group 'arm' relies on deprecated API. Please implement initialize(RobotModel, ...).

This is a bug in `trac_ik_kinematics_plugin`. The issue is tracked [here](https://bitbucket.org/traclabs/trac_ik/issues/62/initialization-change-in-ros-melodic). Looks like an easy fix; somebody should send a pull request.

> Multi-DOF-Joint 'mobipick/virtual_joint' not supported.

This is a warning from the pilz_industrial_motion_planner ([this line](https://github.com/ros-planning/moveit/blob/0d7462f140e03b4c319fa8cce04a47fe3f650c60/moveit_planners/pilz_industrial_motion_planner/src/joint_limits_aggregator.cpp#L118)). Related to https://github.com/ros-planning/moveit/issues/2930. The warning gets printed because there is a floating virtual joint in our model, but the planner doesn't even have to plan for it because we use the base_link as the planning frame, so planning still works despite the warning.

> Unable to update multi-DOF joint 'mobipick/virtual_joint': Failure to lookup transform between 'map' and 'mobipick/base_footprint' with TF exception: "map" passed to lookupTransform argument target_frame does not exist.  [/mobipick/move_group]

I think this is a transient error that goes away as soon as the `map` frame gets published.

**Comment by alexander-sung** [comment]
That's a nice tongue twister title now. 😃

**Comment by mintar** [comment]
Yes, but at least it's specific enough so I don't have to click all 6 similarly-looking titles until I find the one I'm looking for. :)

**Comment by mintar** [comment]
Also should probably have been 3 separate issues, that would make the titles shorter. :-P

**Comment by alexander-sung** [comment]
I considered the same but since I didn't know about their root causes I didn't want to create even more issues. We still can, what seems better than cross-linking multiple issues in case they're related.

**Comment by alexander-sung** [comment]
Closing this as not planned from our side. @mintar wrote [above](https://github.com/DFKI-NI/mobipick_labs/issues/3#issuecomment-1342855111) which updates would be needed for the dependencies.
