### ISSUE TITLE
Use plexmo in the tables demo

### ISSUE THREAD

**Issue by sebastianstock** [DFKI-NI/mobipick_labs#9]
Integrate the `SequentialPlanDispatcher `for dispatching of actions and the `SequentialPlanMonitor` for checking preconditions into the tables demo.

- [X] Move domain to src
- [ ] Create node for uplexmo
- [ ] Update readme

**Comment by alexander-sung** [comment]
It seems this issue is already resolved, right?

- Move domain to src: https://github.com/DFKI-NI/mobipick_labs/blob/noetic/tables_demo_planning/src/tables_demo_planning/pick_n_place_demo.py
- Create node for uplexmo: https://github.com/DFKI-NI/mobipick_labs/blob/noetic/tables_demo_planning/nodes/uplexmo_pick_n_place_demo_node.py
- Update readme: https://github.com/DFKI-NI/mobipick_labs#pick-and-place-demo-using-plexmo

**Comment by sebastianstock** [comment]
It's almost done. You referenced the pick_n_place demo. I did something similar for the tables demo on branch https://github.com/DFKI-NI/mobipick_labs/tree/plexmo_tables_demo. I will check the status of that and create a pull request.

**Comment by alexander-sung** [comment]
Oh, right. I obviously got that mixed up, probably due to the other issue with the pick-and-place demo. I will check as well then.
